language: java
jdk:
- oraclejdk8
- oraclejdk7

notifications:
  email:
    recipients:
    - justin.lee@mongodb.com
    on_success: change
    on_failure: always

services:
- mongodb

#branches:
#  only:
#  - master
#  - aggfluent

install: ./gradlew -q jar --stacktrace
script: ./gradlew -q check --stacktrace
