baseurl = "/morphia/1.2"
languageCode = "en-us"
title = "Morphia"
theme = "learn"
canonifyurls = false

[params]
    disableBreadcrumb = true
    disableNextPrev = true

[[menu.main]]

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Source Code"
identifier = "githubLink"
url = "https://github.com/MorphiaOrg/morphia"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-book'></i> API Documentation"
weight = 9
identifier = "apiDocs"
url = "/javadoc"
