baseurl = "/1.5"
homePageUrl = "https://morphia.dev/"
languageCode = "en-us"
title = "Morphia"
theme = "learn"
canonifyurls = false

[params]
  disableBreadCrumb = true
  disableNextPrev = false
  disableInlineCopyToClipBoard = true
  disableSearch = true

[[menu.main]]

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Source Code"
identifier = "githubLink"
url = "https://github.com/MorphiaOrg/morphia"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-book'></i> API Documentation"
weight = 9
identifier = "apiDocs"
url = "/javadoc"
